#!/bin/zsh

# Get terget path
target="$(cd "$(dirname "${0}")" && pwd)"

# zsh
/bin/zsh -c "cd ${target}/zsh; ./installer"

# nvim
/bin/zsh -c "cd ${target}/nvim; ./installer"

# TeX
/bin/zsh -c "cd ${target}/TeX; ./installer"
